# Generated by Django 4.2.21 on 2025-05-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_users', 'Can manage users'), ('can_manage_tickets', 'Can manage tickets'), ('can_manage_company', 'Can manage company')]},
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
