# Generated by Django 4.2.21 on 2025-05-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_company_profile_mfa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_login_completed',
            field=models.BooleanField(default=False),
        ),
    ]
