# Generated by Django 4.2.21 on 2025-05-12 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_first_login_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password_reset_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password_reset_token_created',
        ),
    ]
