# Generated by Django 5.2 on 2025-05-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_password_reset_fields'),
        ('accounts', '0009_remove_profile_password_reset_token_and_more'),
    ]

    operations = [
    ]
