# Generated by Django 4.2.21 on 2025-05-12 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20250512_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCompanyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_staff', to='accounts.company')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Company Assignment',
                'verbose_name_plural': 'Staff Company Assignments',
                'unique_together': {('staff_user', 'company')},
            },
        ),
    ]
