# Generated by Django 4.2.21 on 2025-05-12 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_staffcompanyassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffcompanyassignment',
            options={'verbose_name': 'Company Assignment', 'verbose_name_plural': 'Company Assignments'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_users', 'Can manage users'), ('can_manage_tickets', 'Can manage tickets'), ('can_manage_company', 'Can manage company'), ('can_view_assigned_companies', 'Can view tickets from assigned companies'), ('can_manage_assigned_tickets', 'Can manage tickets from assigned companies')]},
        ),
        migrations.RenameField(
            model_name='staffcompanyassignment',
            old_name='staff_user',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='staffcompanyassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='is_company_agent',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a company agent with special privileges'),
        ),
        migrations.AlterField(
            model_name='staffcompanyassignment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AlterUniqueTogether(
            name='staffcompanyassignment',
            unique_together={('user', 'company')},
        ),
    ]
