# Generated by Django 5.2 on 2025-05-02 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_families', to='accounts.company')),
            ],
            options={
                'verbose_name_plural': 'Service Families',
                'ordering': ['name'],
                'unique_together': {('name', 'company')},
            },
        ),
    ]
