# Generated by Django 5.2 on 2025-05-02 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_company'),
        ('user_tickets', '0005_ticket_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(null=True, blank = True, on_delete=django.db.models.deletion.CASCADE, related_name='company_tickets', to='accounts.company'),
        ),
    ]
