# Generated by Django 5.2 on 2025-05-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tickets', '0006_ticket_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='company',
        ),
    ]
