# Generated by Django 5.2 on 2025-05-02 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_company'),
        ('user_tickets', '0007_remove_ticket_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_tickets', to='accounts.company'),
        ),
    ]
