# Generated by Django 5.2 on 2025-05-04 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tickets', '0010_ticketcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcomment',
            name='is_internal',
        ),
        migrations.AddField(
            model_name='ticket',
            name='contacts',
            field=models.ManyToManyField(blank=True, help_text='Tag other users from your company who should be involved in this ticket.', limit_choices_to={'company': models.F('created_by__company')}, related_name='tagged_in_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
