# Generated by Django 5.2 on 2025-05-04 04:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tickets', '0011_remove_ticketcomment_is_internal_ticket_contacts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='contacts',
            field=models.ManyToManyField(blank=True, help_text='Tag other users from your company who should be involved in this ticket.', related_name='tagged_in_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
