# Generated by Django 5.2 on 2025-05-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tickets', '0012_alter_ticket_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
