# Generated by Django 5.2 on 2025-05-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tickets', '0013_alter_ticketcomment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='Open', max_length=20),
        ),
    ]
