# Generated by Django 5.2 on 2025-05-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tickets', '0014_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
