# Generated by Django 5.2 on 2025-05-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tickets', '0015_ticket_resolved_at_ticket_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
